/**
 * Local seam over Phosphor icons.
 * App code imports icons from '@/components/ui' — never from '@phosphor-icons/*' directly.
 * Add icons here as needed.
 */
import {
  // Navigation / UI
  ButterflyIcon as Butterfly,
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  ArrowsLeftRightIcon as ArrowsLeftRight,
  PlusIcon as Plus,
  CaretDownIcon as CaretDown,
  CaretLeftIcon as CaretLeft,
  CaretRightIcon as CaretRight,
  CheckIcon as Check,
  CopyIcon as Copy,
  ShareNetworkIcon as ShareNetwork,
  SignInIcon as SignIn,
  SignOutIcon as SignOut,
  XIcon as X,
  ListIcon as List,
  ListChecksIcon as ListChecks,
  GridFourIcon as GridFour,
  HouseIcon as House,
  PencilSimpleIcon as PencilSimple,
  ArrowsClockwiseIcon as ArrowsClockwise,
  ReceiptIcon as Receipt,
  TrashIcon as Trash,
  DotsThreeIcon as DotsThree,
  IdentificationCardIcon as IdentificationCard,
  PlayCircleIcon as PlayCircle,
  PlayIcon as Play,
  ClockIcon as Clock,
  DownloadSimpleIcon as DownloadSimple,

  // Data / Business
  BuildingsIcon as Buildings,
  BriefcaseIcon as Briefcase,
  ChartBarIcon as ChartBar,
  CreditCardIcon as CreditCard,
  CurrencyDollarIcon as CurrencyDollar,
  DatabaseIcon as Database,
  FileTextIcon as FileText,
  GavelIcon as Gavel,
  GlobeIcon as Globe,
  GlobeHemisphereEastIcon as GlobeHemisphereEast,
  LockIcon as Lock,
  MapPinIcon as MapPin,
  ShieldCheckIcon as ShieldCheck,
  StorefrontIcon as Storefront,
  FlagIcon as Flag,
  TagIcon as Tag,

  // Communication
  BellIcon as Bell,
  ChatCircleIcon as ChatCircle,
  ChatTeardropTextIcon as ChatTeardropText,
  EnvelopeSimpleIcon as EnvelopeSimple,
  MailboxIcon as Mailbox,
  MicrophoneStageIcon as MicrophoneStage,
  NewspaperIcon as Newspaper,
  QuestionIcon as Question,

  // Media / Social
  CameraIcon as Camera,
  CalendarBlankIcon as CalendarBlank,
  CloudIcon as Cloud,
  CookieIcon as Cookie,
  CrosshairIcon as Crosshair,
  EyeIcon as Eye,
  EyeSlashIcon as EyeSlash,
  GraduationCapIcon as GraduationCap,
  InstagramLogoIcon as InstagramLogo,
  LinkedinLogoIcon as LinkedinLogo,
  MegaphoneSimpleIcon as MegaphoneSimple,
  RobotIcon as Robot,
  StarIcon as Star,
  TextTIcon as TextT,
  ThreadsLogoIcon as ThreadsLogo,
  UserCircleIcon as UserCircle,
  UsersIcon as Users,
  UsersThreeIcon as UsersThree,
  WrenchIcon as Wrench,
  YoutubeLogoIcon as YoutubeLogo,

  // Status
  CheckCircleIcon as CheckCircle,
  InfoIcon as Info,
  CrownIcon as Crown,
  LightningIcon as Lightning,
  SparkleIcon as Sparkle,
  WarningIcon as Warning,
  WarningCircleIcon as WarningCircle,
  XCircleIcon as XCircle,
  MegaphoneSimpleIcon,
} from '@phosphor-icons/react/dist/ssr';

export {
  // Navigation / UI
  Butterfly,
  ArrowLeft,
  ArrowRight,
  ArrowsLeftRight,
  Plus,
  CaretDown,
  CaretLeft,
  CaretRight,
  Check,
  Copy,
  ShareNetwork,
  SignIn,
  SignOut,
  X,
  List,
  ListChecks,
  GridFour,
  House,
  PencilSimple,
  ArrowsClockwise,
  Receipt,
  Trash,
  DotsThree,
  IdentificationCard,
  PlayCircle,
  Play,
  Clock,
  DownloadSimple,

  // Data / Business
  Buildings,
  Briefcase,
  ChartBar,
  CreditCard,
  CurrencyDollar,
  Database,
  FileText,
  Gavel,
  Globe,
  GlobeHemisphereEast,
  Lock,
  MapPin,
  ShieldCheck,
  Storefront,
  Flag,
  Tag,

  // Communication
  Bell,
  ChatCircle,
  ChatTeardropText,
  EnvelopeSimple,
  Mailbox,
  MicrophoneStage,
  Newspaper,
  Question,

  // Media / Social
  Camera,
  CalendarBlank,
  Cloud,
  Cookie,
  Crosshair,
  Eye,
  EyeSlash,
  GraduationCap,
  InstagramLogo,
  LinkedinLogo,
  MegaphoneSimple,
  Robot,
  Star,
  TextT,
  ThreadsLogo,
  UserCircle,
  Users,
  UsersThree,
  Wrench,
  YoutubeLogo,

  // Status
  CheckCircle,
  Info,
  Crown,
  Lightning,
  Sparkle,
  Warning,
  WarningCircle,
  XCircle,
  MegaphoneSimpleIcon,
};

// Utility
export { cn } from '@heroui/react';
